global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'devops-dashboard'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['devops-dashboard:15000']
